#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class Solution

    buildFibonacci: (end)->
        @result = [1,2]
        count = 2
        value = 0
        while value < end
            firstNumber = @result[count-2]
            secondNumber = @result[count-1]
            value = firstNumber + secondNumber
            @result.push value
            count++
        return @

    evens: ->
        newResult = []
        for term in @result
            if term % 2 is 0 then newResult.push term
        @result = newResult
        return @

    sum: ->
        total = 0
        for number in @result
            total += number
        @result = total
        return @

module.exports = Solution